# For general use
# SAMPLES_OF_DATA_TO_LOOK_AT = 30
# SAMPLES_OF_DATA_TO_LOOK_AT = 15 * 24
# SAMPLES_OF_DATA_TO_LOOK_AT = 15 * 8
DAYS_IN_AN_INPUT = 15
SAMPLES_OF_DATA_TO_LOOK_AT = DAYS_IN_AN_INPUT * 8
